### ISSUE TITLE
Author field return the same user multiple times

### ISSUE THREAD

**Issue by damsfx** [Dynamedia/wn-posts-plugin#2]
If more than one backend users are registered, when editing a post, `post[autor]` and `post[editor]` fields show the same (current?) user's name multiple times.
https://github.com/Dynamedia/wn-posts-plugin/blob/b40abb74d879761c6c53925be46723f271046200/models/Profile.php#L97-L100

**Comment by robballantyne** [comment]
Thanks for your report. I expect to fix this next week. Sorry for the inconvenience.

Rob

**Comment by robballantyne** [comment]
This should be fixed by commit e30184c5732a53a85edcc7e1ba8d998ffce7d622 

Notes:
This bug does not appear in the October CMS version. I have not fully investigated, but there may be some divergence between the forks relation loading.
