### ISSUE TITLE
'Media\Classes\MediaLibrary' not found

### ISSUE THREAD

**Issue by damsfx** [Dynamedia/wn-posts-plugin#5]
In WinterCMS `Media\Classes\MediaLibrary` does'nt exist, it may be `System\Classes\MediaLibrary`.

https://github.com/Dynamedia/wn-posts-plugin/search?q=Media%5CClasses%5CMediaLibrary

**Comment by robballantyne** [comment]
Thanks. 

This is a hangover from an October update, I will push an update with a fix.

**Comment by robballantyne** [comment]
Fixed by e443770

**Comment by damsfx** [comment]
Thank's !
